# Generated by Django 2.2.3 on 2019-07-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_paid',
            new_name='has_paid',
        ),
    ]
