# Generated by Django 2.2.3 on 2019-07-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190724_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='has_paid',
            new_name='premium',
        ),
    ]
