# Generated by Django 2.2.3 on 2019-07-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_query_query_spec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='query_spec',
        ),
        migrations.AddField(
            model_name='query',
            name='query_type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature')], default='Bug', max_length=7),
        ),
    ]
