# Generated by Django 2.2.3 on 2019-07-23 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Query'),
        ),
    ]
