# Generated by Django 2.2.3 on 2019-07-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_query_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('In progess', 'In progess'), ('Done', 'Done')], default='To do', max_length=10),
        ),
    ]
