# Generated by Django 2.2.3 on 2019-07-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_query_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
