# Generated by Django 2.2.3 on 2019-07-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_query_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_type',
            field=models.CharField(choices=[('bug', 'bug'), ('feature', 'feature')], default='bug', max_length=7),
        ),
    ]
