# Generated by Django 2.2.3 on 2019-07-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20190725_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature')], default='Bug', max_length=7),
        ),
    ]
