# Generated by Django 2.2.3 on 2019-07-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20190728_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='total_l',
            field=models.IntegerField(default=0),
        ),
    ]
