# Generated by Django 2.2.3 on 2019-07-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_query_total_l'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='total_l',
            new_name='total_like',
        ),
    ]
