# Generated by Django 2.2.3 on 2019-07-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20190729_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='content',
            new_name='description',
        ),
    ]
