# Generated by Django 2.2.3 on 2019-07-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20190729_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='description',
            new_name='content',
        ),
    ]
