# Generated by Django 2.2.3 on 2019-07-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20190729_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='total_like',
        ),
        migrations.AlterField(
            model_name='query',
            name='content',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
